# Copyright 2025 Bastien BYRA

name: Lint CI

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'
    paths:
      - '**.js'
      - 'package.json'
      - 'package-lock.json'
      - '.eslintrc*'
  pull_request:
    branches:
      - '**'
    paths:
      - '**.js'
      - 'package.json'
      - 'package-lock.json'
      - '.eslintrc*'

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
