name: Tests CI

on:
  push:
    paths:
      - '**.js'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    paths:
      - '**.js'
      - 'package.json'
      - 'package-lock.json'

env:
  IMAGE_VERSION: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Run unit test
        run: npm run test
    
  # Ensure the image can be build
  test-build:
    name: Docker Build Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: |
            ghcr.io/bastienbyra/cpe-mapper:${{ env.IMAGE_VERSION }}