# Copyright 2025 Bastien BYRA

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Tests CI

on:
  push:
    paths:
      - '**.js'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    paths:
      - '**.js'
      - 'package.json'
      - 'package-lock.json'

env:
  IMAGE_VERSION: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Run unit test
        run: npm run test

      # Build a package of the application we can pass to other jobs
      - name: Build package
        run: npm pack
      - uses: actions/upload-artifact@v4
        with:
          name: cpe-mapper-package
          path: bastienbyra-cpe-mapper-*.tgz
    
  # Ensure the image can be build
  test-build:
    name: Docker Build test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Test Docker build
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: |
            ghcr.io/bastienbyra/cpe-mapper:${{ env.IMAGE_VERSION }}

  test-npm-publish:
    name: NPM publish test
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Download package artifact
        uses: actions/download-artifact@v4
        with:
          name: cpe-mapper-package

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'

      - name: Test publish
        run: npm publish --dry-run *.tgz