# Copyright 2025 Bastien BYRA

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: GHA Test CI

on: [push]

jobs:
  build-image:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Test GHA Entrypjnt/Action
        uses: ./
        with:
          input-file: testdata/bom.test.json
          output-file: testdata/resultbom.test.json
          verbose: true
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: new-sbom
          path: testdata/resultbom.test.json
          retention-days: 1