name: Tests CI

on:
  push:
    paths:
      - '**.js'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    paths:
      - '**.js'
      - 'package.json'
      - 'package-lock.json'

env:
  IMAGE_VERSION: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Run unit test
        run: npm run test